import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navbar";
import ModelProvider from "@/providers/model-provider";
import ToastProvider from "@/providers/toast.provider";

const font = Urbanist({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Store ",
  description: "Generated by marwa ",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <ModelProvider />
        <ToastProvider/>
        <Navbar/>
        {children}
        <Footer/>

      </body>
    </html>
  );
}
